object Versions {
    const val arrow = "1.0.1"
    const val gradle = "4.0.1"
    const val ktlint = "0.48.2"
    const val kotlin = "1.7.10"
    const val coroutines = "1.6.4"
    const val gradleVersions = "0.42.0"
    const val arch = "2.5.1"
    const val coreKtx = "1.9.0"
    const val archTest = "2.1.0"
    const val truth = "1.1.3"
    const val material = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val hilt = "2.44"
    const val okHttp = "4.10.0"
    const val timber = "5.0.1"
    const val glide = "4.14.2"
    const val retrofit = "2.9.0"
    const val junit = "4.13.2"
    const val testRunner = "1.5.2"
    const val espresso = "3.5.1"
    const val mockk = "1.13.3"
    const val navigationComponent = "2.5.3"
    const val fragment = "1.5.5"
}